### ISSUE TITLE
System.Net.WebException - (401) Unauthorized

### ISSUE THREAD

**Issue by marcogruhl** [andypiper/TwitterDotNetCore#3]
Hello Andy,

i think this is not a real issue on your side, but maybe you can help me or have just some advice.

I came across your repo while trying to implement the user scope for the [TwitterSharp](https://github.com/Xwilarg/TwitterSharp) API. I also recognized that you starred this repository.

I generated the 4 tokens ( consumer-key, consumer-secret, access-token, access-secret) from the twitter developer portal. I also regenerated them completely but always get unauthorized. The authorization header looks good (at least to me) What could i have done wrong?

thanks in advance,
marco

**Comment by andypiper** [comment]
Hmm, I'm not sure about this unfortunately (and I need to archive this repository as it is not something I'm doing any active work on).

Are you able to call the API via any other means e.g. using Postman or twurl - does your application and project have permission to call the endpoints / functions you are trying to use? if you're trying to access the v1.1 streaming API for example, you can't do that any more.

A couple of other small things to check:

- your client machine's time needs to be accurate as OAuth requires it
- are you using a modern / recent version of Windows, or an older one? The reason I ask about that is that I know some older Windows versions have outdated TLS implementations that can no longer connect to the Twitter API endpoints.

Apart from that I'd have to suggest the Twitter developer forums for assistance.

I'm going to close this since it is not an issue with this project itself.

**Comment by marcogruhl** [comment]
Thank you for your answer and sorry for the inconvenience. For completion: I can access all "App-Endpoints" with the bearer token. I just call v2 endpoints. Time and Windows version are up to date. I will investigate further by my self.
PS: do you still have access to the twitter API and does this program still run? If yes, i can use it as "reference" and try to fix my token problems.
Tank you anyway, marco
